import type { Metadata } from "next";
import { Quicksand } from "next/font/google";
import "./globals.css";
import { AppSidebar } from "@/components/Sidebar";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";
import { Toaster } from "@/components/ui/sonner";

const quicksand = Quicksand({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${quicksand.className}  antialiased flex h-screen bg-gray-100`}
      >
        <SidebarProvider>
          <AppSidebar />
          <main className="flex-1 bg-gray-50">{children}</main>
          <Toaster />
        </SidebarProvider>
      </body>
    </html>
  );
}
